# Generated by Django 5.1.3 on 2024-11-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='alojamientoasignacion',
            name='alojamiento',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='id_estado',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='viaje',
        ),
        migrations.RemoveField(
            model_name='viajecolaborador',
            name='viaje',
        ),
        migrations.DeleteModel(
            name='EstadoAlojamiento',
        ),
        migrations.DeleteModel(
            name='Alojamiento',
        ),
        migrations.DeleteModel(
            name='AlojamientoAsignacion',
        ),
        migrations.DeleteModel(
            name='EstadoViaje',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
        migrations.DeleteModel(
            name='Viaje',
        ),
        migrations.DeleteModel(
            name='ViajeColaborador',
        ),
    ]
