# Generated by Django 5.1.3 on 2024-11-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionTiempoTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField(auto_now_add=True)),
                ('tiempo_estimado', models.FloatField()),
                ('modelo_utilizado', models.CharField(max_length=50)),
            ],
        ),
    ]
